version: "2"

services:
  postgres:
    restart: unless-stopped
    networks:
      - default
    env_file: .env
    image: postgres:11
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


networks:
  default:
